package graphical_user_interface;

public enum BlueEvent {
	BOX_LOADED, BOX_UNLOADED,
	CRATE_LOADED, CRATE_UNLOADED,
	BARREL_LOADED, BARREL_UNLOADED,
	ALLICARGO_LOADED, ALLICARGO_UNLOADED,
	TREASURE_LOADED, TREASURE_UNLOADED,
	EASTERN_ANCHOR_RAISED, WESTERN_ANCHOR_RAISED,
	SOUTHERN_CANNON_SHOT, NORTHERN_CANNON_SHOT,
	BRIDGE_RAISED;
}